#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role
    - name: Install Docker
      package:
        name: docker
        state: present
      register: y 
    
    - name: Start Docker Daemon
      service:
        name: docker
        state: started
        enabled: yes
      when: y.failed == false