#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_role
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: true

- name: Download CloudWatch Agent package
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb

- name: Install CloudWatch Agent
  apt:
    deb: /tmp/amazon-cloudwatch-agent.deb
    state: present

- name: Create CloudWatch Agent config file
  copy:
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    content: |
      {
        "metrics": {
          "metrics_collected": {
            "mem": {
              "measurement": [
                "mem_used_percent",
                "mem_available"
              ],
              "metrics_collection_interval": 60
            },
            "disk": {
              "resources": ["/"],
              "measurement": [
                "used_percent",
                "free"
              ],
              "metrics_collection_interval": 60
            }
          }
        }
      }
    owner: root
    group: root
    mode: 0644

- name: Start CloudWatch Agent
  shell: |
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config \
    -m ec2 \
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
    -s
  args:
    executable: /bin/bash

- name: Enable CloudWatch Agent to start on boot
  systemd:
    name: amazon-cloudwatch-agent
    enabled: true
    state: started
