name: Infrastructure Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format Check
        id: fmt_check
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Format
        if: steps.fmt_check.outcome != 'success'
        run: terraform fmt

  validate:
    name: Terraform Validate
    needs: fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -var="instance_key_name=${{ vars.INSTANCE_KEY_NAME }}"
      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: Terraform/tfplan
    
  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: Terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply tfplan
      - name: Get outputs
        id: get-outputs
        run: |
          VM_PUBLIC_IP=$(terraform output -raw vm_public_ip | sed -n '1p')
          DB_ENDPOINT=$(terraform output -raw db_endpoint | sed -n '1p')
          echo "vm_public_ip=$VM_PUBLIC_IP" >> "$GITHUB_OUTPUT"
          echo "db_endpoint=$DB_ENDPOINT" >> "$GITHUB_OUTPUT"
    
    outputs:
      vm_public_ip: ${{ steps.get-outputs.outputs.vm_public_ip }}
      db_endpoint: ${{ steps.get-outputs.outputs.db_endpoint }}

  ansible:
    name: Ansible Provision
    needs: apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ansible
        run: pip install ansible
      - name: Run Ansible playbook
        run: |
          cd Ansible
          ansible-playbook main.yaml -i inventory.ini -e "ansible_ssh_private_key_file=${{secrets.SSH_PRIVATE_KEY}}"
        env:
          ANSIBLE_HOSTS: |
            [servers]
            app_server ansible_host=${{ needs.apply.outputs.vm_public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/${{secrets.SSH_PRIVATE_KEY_NAME}}.pem

  destroy:
    name: Terraform Destroy
    needs: apply
    runs-on: ubuntu-latest
    environment: prod
    if: github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
 
